[nixpacks]
plan = "bun"

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmd = "bun install"

[phases.build]
cmd = "bun run build"

[phases.start]
cmd = "bun run serve"

[phases.start.cache]
paths = ["node_modules", ".cache", "public"]